-- Deck CMS: slides for the public pitch decks (/deck, /tenant-deck),
-- edited via /deck/admin and /tenant-deck/admin on the marketing site.
CREATE TABLE IF NOT EXISTS deck_slides (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  deck TEXT NOT NULL CHECK (deck IN ('tenant', 'whitelabel')),
  position INTEGER NOT NULL,
  template TEXT NOT NULL,
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deck_slides_deck_pos ON deck_slides (deck, position);

-- Service-role only (marketing API routes); no anon/authenticated policies.
ALTER TABLE deck_slides ENABLE ROW LEVEL SECURITY;

-- Seed from the hand-built static decks — only into an empty table.
INSERT INTO deck_slides (deck, position, template, content)
SELECT v.deck, v.position, v.template, v.content
FROM (VALUES
  ('tenant', 1, 'cover', $j${"mark": {"en": "Balkina AI · For Your Business", "sr": "Balkina AI · Za vaš biznis"}, "title": {"en": "Automate your booking & fill up your calendar", "sr": "Automatizujte zakazivanje i popunite svoj kalendar"}, "lede": {"en": "with Balkina — an AI booking platform where new customers find you, regulars rebook more often, and your schedule takes care of itself.", "sr": "uz Balkinu — AI platformu za zakazivanje na kojoj vas novi klijenti pronalaze, stalni se vraćaju češće, a raspored se vodi sam."}}$j$::jsonb),
  ('tenant', 2, 'types', $j${"eyebrow": {"en": "Built For", "sr": "Napravljeno za"}, "items": [{"label": {"en": "Salons", "sr": "Salone"}}, {"label": {"en": "Barbershops", "sr": "Berbernice"}}, {"label": {"en": "Spas", "sr": "Spa centre"}}, {"label": {"en": "Trainers", "sr": "Trenere"}}, {"label": {"en": "Clinics", "sr": "Ordinacije"}}, {"label": {"en": "Dentists", "sr": "Stomatologe"}}, {"label": {"en": "Physiotherapists", "sr": "Fizioterapeute"}}, {"label": {"en": "Nail studios", "sr": "Nail studije"}}, {"label": {"en": "Massage", "sr": "Masaže"}}, {"label": {"en": "Yoga studios", "sr": "Joga studije"}}, {"label": {"en": "Gyms", "sr": "Teretane"}}, {"label": {"en": "Restaurants", "sr": "Restorane"}}, {"label": {"en": "Cafés", "sr": "Kafiće"}}, {"label": {"en": "Tour operators", "sr": "Turističke agencije"}}, {"label": {"en": "Experiences", "sr": "Doživljaje"}}]}$j$::jsonb),
  ('tenant', 3, 'problem', $j${"eyebrow": {"en": "The Problem", "sr": "Problem"}, "title": {"en": "Bookings you never even saw are going to someone else", "sr": "Rezervacije koje niste ni videli odlaze nekom drugom"}, "gaps": [{"heading": {"en": "Hard to discover", "sr": "Teško vas je pronaći"}, "text": {"en": "New customers can't find you — discovery today is word of mouth and whoever shows up first on Google", "sr": "Novi klijenti ne znaju za vas — otkrivanje se danas svodi na preporuke i na to ko prvi iskoči na Google-u"}}, {"heading": {"en": "Slow to book", "sr": "Sporo zakazivanje"}, "text": {"en": "Booking happens over calls, DMs and email back-and-forth — hours to close what should take seconds", "sr": "Rezervacije idu preko poziva, poruka i mejlova — satima se zatvara ono što traje sekunde"}}, {"heading": {"en": "Missed demand", "sr": "Propuštena tražnja"}, "text": {"en": "Calls while your hands are busy and messages at midnight go unanswered — those bookings go elsewhere", "sr": "Pozivi dok su vam ruke zauzete i poruke u ponoć ostaju bez odgovora — te rezervacije odu drugom"}}, {"heading": {"en": "Forgotten regulars", "sr": "Zaboravljeni stalni klijenti"}, "text": {"en": "Your best customers drift — not because they left, but because nobody reminded them they're due", "sr": "Najbolji klijenti se osipaju — ne zato što su otišli, već zato što ih niko nije podsetio da je vreme"}}]}$j$::jsonb),
  ('tenant', 4, 'points-chat', $j${"eyebrow": {"en": "The Solution", "sr": "Rešenje"}, "title": {"en": "Balkina AI receptionist that never sleeps", "sr": "Balkina AI recepcioner koji nikad ne spava"}, "points": [{"strong": {"en": "New customers will easily discover your business:", "sr": "Novi klijenti će lako otkriti vaš biznis:"}, "text": {"en": "find real-time availability and book your services — day or night", "sr": "vide dostupnost u realnom vremenu i zakazuju vaše usluge — danju i noću"}}, {"strong": {"en": "Instant confirmation or your approval:", "sr": "Trenutna potvrda ili vaše odobrenje:"}, "text": {"en": "you decide which bookings need a yes from you", "sr": "vi odlučujete koje rezervacije traže vaš pristanak"}}, {"strong": {"en": "Every booking lands in one calendar:", "sr": "Svaka rezervacija stiže u jedan kalendar:"}, "text": {"en": "with the customer's details and history attached", "sr": "sa podacima i istorijom klijenta"}}], "msgs": [{"who": "guest", "text": {"en": "Any openings for a cut and beard trim tomorrow after 5?", "sr": "Ima li termina za šišanje i bradu sutra posle 17h?"}}, {"who": "bot", "text": {"en": "Marco has 5:30 or 6:15 free tomorrow. Both take 45 minutes — which suits you?", "sr": "Marko sutra ima slobodno u 17:30 ili 18:15. Oba termina traju 45 minuta — koji vam odgovara?"}}, {"who": "guest", "text": {"en": "5:30, please.", "sr": "17:30, molim."}}]}$j$::jsonb),
  ('tenant', 5, 'points', $j${"eyebrow": {"en": "New Customers", "sr": "Novi klijenti"}, "title": {"en": "Grow your business by helping new customers find you", "sr": "Rastite tako što vas novi klijenti lako pronalaze"}, "points": [{"strong": {"en": "You'll be discovered in the app:", "sr": "Bićete otkriveni u aplikaciji:"}, "text": {"en": "when people nearby search for you, our AI will display your services with open time slots", "sr": "kada ljudi u blizini traže vašu uslugu, naš AI prikazuje vaše usluge sa slobodnim terminima"}}, {"strong": {"en": "Your own booking link:", "sr": "Vaš lični link za rezervacije:"}, "text": {"en": "add your private Balkina link on Instagram, Google profiles, and WhatsApp replies. Customers book you directly", "sr": "dodajte svoj Balkina link na Instagram, Google profil i u WhatsApp odgovore. Klijenti vas rezervišu direktno"}}, {"strong": {"en": "Reviews build your reputation:", "sr": "Recenzije grade vašu reputaciju:"}, "text": {"en": "good reviews mean you are presented with priority when customers search", "sr": "dobre recenzije znače prioritet kada klijenti pretražuju"}}], "kicker": {"en": "Let new customers find you easily", "sr": "Neka vas novi klijenti lako pronađu"}}$j$::jsonb),
  ('tenant', 6, 'points', $j${"eyebrow": {"en": "Regular Customers", "sr": "Stalni klijenti"}, "title": {"en": "Retain loyal customers by making it easy to rebook", "sr": "Zadržite verne klijente uz lako ponovno zakazivanje"}, "points": [{"strong": {"en": "Use Balkina to learn their rhythm:", "sr": "Balkina uči njihov ritam:"}, "text": {"en": "when a regular is due, AI nudges them to book again before they drift", "sr": "kada je stalnom klijentu vreme, AI ga podseti da zakaže pre nego što se izgubi"}}, {"strong": {"en": "Automatic reminders:", "sr": "Automatski podsetnici:"}, "text": {"en": "AI and SMS reminders keep appointments on time and reduce no-shows", "sr": "AI i SMS podsetnici drže termine na vremenu i smanjuju nedolaske"}}, {"strong": {"en": "Remember every customer:", "sr": "Zapamtite svakog klijenta:"}, "text": {"en": "make returning seamless by learning their history and preferences in one profile", "sr": "povratak je bez napora uz istoriju i navike u jednom profilu"}}], "kicker": {"en": "Let your loyal customers come back often", "sr": "Neka se verni klijenti često vraćaju"}}$j$::jsonb),
  ('tenant', 7, 'divider', $j${"title": {"en": "The Platform", "sr": "Platforma"}, "lede": {"en": "Everything behind the counter, in one place", "sr": "Sve iza pulta, na jednom mestu"}, "mock": "calendar"}$j$::jsonb),
  ('tenant', 8, 'points', $j${"eyebrow": {"en": "A Central Command", "sr": "Centralna komanda"}, "title": {"en": "A booking suite that fits businesses of all sizes", "sr": "Sistem za zakazivanje za biznise svih veličina"}, "points": [{"strong": {"en": "Manage services, staff, and schedules:", "sr": "Upravljajte uslugama, osobljem i rasporedima:"}, "text": {"en": "durations, buffer times, days off, per-staff availability, multiple locations", "sr": "trajanja, pauze, slobodni dani, dostupnost po zaposlenom, više lokacija"}}, {"strong": {"en": "Manage appointments end to end:", "sr": "Vodite termine od početka do kraja:"}, "text": {"en": "approve, reschedule, and reach customers by call, text, WhatsApp, or email", "sr": "odobrite, pomerite i kontaktirajte klijente pozivom, porukom, WhatsApp-om ili mejlom"}}, {"strong": {"en": "Offer coupons and package deals:", "sr": "Ponudite kupone i pakete:"}, "text": {"en": "entice customers with coupons and upsell with package deals", "sr": "privucite klijente kuponima i povećajte prodaju paketima"}}], "kicker": {"en": "CRM suite, without the complexity", "sr": "CRM alati, bez komplikacija"}}$j$::jsonb),
  ('tenant', 9, 'points', $j${"eyebrow": {"en": "No More Double Booking", "sr": "Bez duplih rezervacija"}, "title": {"en": "Keep all your existing calendars in sync", "sr": "Držite sve postojeće kalendare usklađene"}, "points": [{"strong": {"en": "Google Calendar, two-way:", "sr": "Google kalendar, dvosmerno:"}, "text": {"en": "Balkina bookings appear in Google; your busy times block Balkina automatically", "sr": "Balkina rezervacije se pojavljuju u Google-u; vaši zauzeti termini automatski blokiraju Balkinu"}}, {"strong": {"en": "iCal everywhere:", "sr": "iCal svuda:"}, "text": {"en": "export to Apple Calendar and Outlook; import Airbnb, Calendly, and others to stay double-booking-proof", "sr": "izvezite u Apple Calendar i Outlook; uvezite Airbnb, Calendly i druge — bez duplih rezervacija"}}, {"strong": {"en": "Sell on the travel platforms?", "sr": "Prodajete na turističkim platformama?"}, "text": {"en": "connect Bokun and your Viator, GetYourGuide, and Airbnb Experiences bookings flow straight in", "sr": "povežite Bokun i rezervacije s Viator-a, GetYourGuide-a i Airbnb Experiences-a stižu same"}}], "kicker": {"en": "", "sr": ""}}$j$::jsonb),
  ('tenant', 10, 'points', $j${"eyebrow": {"en": "Hospitality", "sr": "Ugostiteljstvo"}, "title": {"en": "Balkina AI books tables and ticketed evenings, too", "sr": "Balkina AI rezerviše i stolove i večeri s ulaznicama"}, "points": [{"strong": {"en": "Table reservations:", "sr": "Rezervacije stolova:"}, "text": {"en": "party size, your open hours, and your confirmation — you stay in control of the floor", "sr": "broj gostiju, vaše radno vreme i vaša potvrda — vi držite salu pod kontrolom"}}, {"strong": {"en": "Ticketed experiences:", "sr": "Doživljaji s ulaznicama:"}, "text": {"en": "brunches, tastings, holiday dinners with per-person pricing, capacity, and RSVPs", "sr": "branč, degustacije i praznične večere sa cenom po osobi, kapacitetom i prijavama"}}, {"strong": {"en": "The same one dashboard:", "sr": "Ista jedna tabla:"}, "text": {"en": "runs it all, from a single table for two to a sold-out New Year's Eve", "sr": "vodi sve — od stola za dvoje do rasprodatog dočeka Nove godine"}}], "kicker": {"en": "", "sr": ""}}$j$::jsonb),
  ('tenant', 11, 'divider', $j${"title": {"en": "Get Started", "sr": "Počnite"}, "lede": {"en": "Free to try. Live in an afternoon", "sr": "Besplatno za probu. Aktivno za jedno popodne"}, "mock": "booking"}$j$::jsonb),
  ('tenant', 12, 'points', $j${"eyebrow": {"en": "Easy Setup", "sr": "Lako podešavanje"}, "title": {"en": "Free to start. Live in an afternoon", "sr": "Besplatno za početak. Aktivno za jedno popodne"}, "points": [{"strong": {"en": "Create your account:", "sr": "Napravite nalog:"}, "text": {"en": "sign up free in minutes, no credit card required", "sr": "registrujte se besplatno za par minuta, bez kreditne kartice"}}, {"strong": {"en": "Add your services and staff:", "sr": "Dodajte usluge i osoblje:"}, "text": {"en": "set durations, prices and working hours — Balkina builds your booking page", "sr": "podesite trajanja, cene i radno vreme — Balkina pravi vašu stranicu za rezervacije"}}, {"strong": {"en": "Share your link and go live:", "sr": "Podelite svoj link i krenite:"}, "text": {"en": "your first booking can arrive the same day", "sr": "prva rezervacija može stići istog dana"}}], "kicker": {"en": "No hardware and nothing to install", "sr": "Bez opreme i bez instalacija"}}$j$::jsonb),
  ('tenant', 13, 'pricing', $j${"eyebrow": {"en": "Pricing", "sr": "Cene"}, "title": {"en": "Start free. Grow when you do", "sr": "Počnite besplatno. Rastite svojim tempom"}, "kicker": {"en": "7-day free trial on every plan — no credit card, cancel anytime", "sr": "7 dana besplatne probe uz svaki plan — bez kartice, otkažite bilo kad"}, "plans": [{"name": "Solo", "price": "€5", "per": {"en": "/mo", "sr": "/mes"}, "aud": {"en": "For individuals getting started", "sr": "Za pojedince na početku"}, "line": {"en": "1 staff · 1 location · 20 bookings/mo", "sr": "1 zaposleni · 1 lokacija · 20 rezervacija/mes"}, "popular": false, "badge": {"en": "", "sr": ""}}, {"name": "Solo Pro", "price": "€19", "per": {"en": "/mo", "sr": "/mes"}, "aud": {"en": "For serious solo professionals", "sr": "Za ozbiljne solo profesionalce"}, "line": {"en": "1 staff · 1 location · Unlimited bookings", "sr": "1 zaposleni · 1 lokacija · Neograničene rezervacije"}, "popular": false, "badge": {"en": "", "sr": ""}}, {"name": "Team", "price": "€49", "per": {"en": "/mo", "sr": "/mes"}, "aud": {"en": "For small teams", "sr": "Za male timove"}, "line": {"en": "Up to 5 staff · 2 locations · +€6/additional staff", "sr": "Do 5 zaposlenih · 2 lokacije · +6 €/dodatni zaposleni"}, "popular": true, "badge": {"en": "Most Popular", "sr": "Najpopularniji"}}, {"name": "Scale", "price": "€99", "per": {"en": "/mo", "sr": "/mes"}, "aud": {"en": "For growing businesses", "sr": "Za rastuće biznise"}, "line": {"en": "Up to 15 staff · 5 locations · +€6/additional staff", "sr": "Do 15 zaposlenih · 5 lokacija · +6 €/dodatni zaposleni"}, "popular": false, "badge": {"en": "", "sr": ""}}]}$j$::jsonb),
  ('tenant', 14, 'cta', $j${"eyebrow": {"en": "Get Started", "sr": "Počnite"}, "title_pre": {"en": "Put your bookings on", "sr": "Prebacite rezervacije na"}, "title_em": {"en": "autopilot", "sr": "autopilot"}, "lede": {"en": "Create your account, add your services and staff, and share your link — you can take your first booking today", "sr": "Napravite nalog, dodajte usluge i osoblje i podelite svoj link — prvu rezervaciju možete primiti već danas"}, "btn_label": {"en": "Start your free trial", "sr": "Započnite besplatnu probu"}, "btn_url": "https://balkina.ai/join", "dlnote": {"en": "Download our app to see how your customers will experience it", "sr": "Preuzmite našu aplikaciju i pogledajte kako će je vaši klijenti doživeti"}}$j$::jsonb),
  ('whitelabel', 1, 'wl-cover', $j${"mark": "Balkina AI · White Label", "title": "Your property.\nYour app.\nOne concierge.", "sub": "A private, branded booking & community platform for resorts, marinas, and mixed-use destinations — serving the two audiences every great property depends on: its tenants and its residents."}$j$::jsonb),
  ('whitelabel', 2, 'wl-premise', $j${"eyebrow": "The Premise", "title": "You built a destination.", "lede": "Restaurants and cafés, a spa and a marina, boutiques, events, private residences — dozens of experiences at one address. And your guests deserve to experience it as one seamless thread — not a phone number here, a walk-in there, a website that doesn't follow through.", "catalogue": ["Restaurants", "Spa & Wellness", "Marina", "Boutiques", "Fitness", "Events", "Residences"]}$j$::jsonb),
  ('whitelabel', 3, 'wl-gaps', $j${"eyebrow": "What Fragmentation Costs", "title": "Existing challenges.", "gaps": [{"heading": "Discovery", "text": "Guests don't know what events and services are on-site — or how to book them."}, {"heading": "Engagement", "text": "You own the address — not the relationship with your residents and guests."}, {"heading": "Control", "text": "No unified booking for tenants — no visibility and data for the property owner."}], "kicker": "Empty slots, under-filled evenings — a premium destination with a fragmented digital experience."}$j$::jsonb),
  ('whitelabel', 4, 'wl-duo', $j${"eyebrow": "Our Thesis", "title": "A great property serves two audiences.", "cards": [{"heading": "Your tenants", "text": "The businesses that fill your destination with life. They need customers and calm operations — not another piece of software to wrestle."}, {"heading": "Your residents", "text": "The people who chose to live in your world. They deserve recognition, a direct line to you, and a calendar worth staying for."}], "kicker": "One branded app — your name on it — serves both. Balkina runs quietly underneath."}$j$::jsonb),
  ('whitelabel', 5, 'wl-divider', $j${"numeral": "I", "chapter": "Chapter One", "title": "Tenant support\n& management", "lede": "Bookings as a service — provided by you, to every business on your property."}$j$::jsonb),
  ('whitelabel', 6, 'wl-chat', $j${"eyebrow": "I · Seamless Bookability", "title": "Every tenant, seamlessly bookable.", "points": [{"strong": "One app for the whole property.", "text": "Restaurants, spa, activities, services — every business listed, browsed, and booked in seconds."}, {"strong": "Real-time availability", "text": "with instant confirmation, approvals and deposits where the business wants them."}, {"strong": "Your world only.", "text": "Guests discover and book what's inside your property — never a competitor."}, {"strong": "And when they'd rather just ask", "text": "— the AI concierge takes it from there."}], "msgs": [{"who": "guest", "text": "A massage after our sail on Saturday — and dinner for four at eight."}, {"who": "concierge", "text": "With pleasure. Spa Azure has 5:30 free after your charter, and I'm holding a table for four at Terrace at 8:00."}, {"who": "guest", "text": "Book both."}]}$j$::jsonb),
  ('whitelabel', 7, 'wl-points', $j${"eyebrow": "I · Management", "title": "A five-star back-office, included.", "points": [{"strong": "A full dashboard for every business", "text": "— services, staff, schedules, approvals, customers — with calendar sync to Google, iCal, and the travel platforms they already sell on."}, {"strong": "Onboarding in minutes.", "text": "Invite a business, or approve its application; staff, hours and a storefront are provisioned automatically."}, {"strong": "Nothing to learn twice.", "text": "No new hardware, no POS migration, no IT project."}], "kicker": "You're not selling your tenants software. You're providing them customers."}$j$::jsonb),
  ('whitelabel', 8, 'wl-points', $j${"eyebrow": "I · One Community of Businesses", "title": "Speak to every business at once — or precisely.", "points": [{"strong": "Message all tenants, a selection, or a whole category", "text": "— every restaurant before the regatta; the wellness group before the retreat."}, {"strong": "Under your name.", "text": "Announcements, seasonal pushes, and operational notices arrive from the property, elegantly."}, {"strong": "One view of the destination.", "text": "Bookings, campaigns, and activity across every business — finally in one place."}], "kicker": ""}$j$::jsonb),
  ('whitelabel', 9, 'wl-divider', $j${"numeral": "II", "chapter": "Chapter Two", "title": "Resident support\n& management", "lede": "Turn an address into a community."}$j$::jsonb),
  ('whitelabel', 10, 'wl-points', $j${"eyebrow": "II · Recognition", "title": "Your residents, known by name.", "points": [{"strong": "Verified in seconds.", "text": "A private code — or a personal invitation by email, SMS, or WhatsApp. No paperwork, no approval queue."}, {"strong": "Each kind of resident, recognized as such:", "text": "homeowners, renters, commercial owners."}, {"strong": "The concierge greets them accordingly.", "text": "“Welcome back — Villa 12.”"}], "kicker": ""}$j$::jsonb),
  ('whitelabel', 11, 'wl-points', $j${"eyebrow": "II · Connection", "title": "A direct line to the people who matter most.", "points": [{"strong": "Resident-only announcements", "text": "— visible to your community, invisible to passing visitors."}, {"strong": "Reach exactly who you mean.", "text": "All members, or homeowners, renters, or commercial owners alone — by push, to their pocket."}, {"strong": "News, notices, and privileges,", "text": "delivered under your brand rather than a printed flyer in a lobby."}], "kicker": ""}$j$::jsonb),
  ('whitelabel', 12, 'wl-points', $j${"eyebrow": "II · Togetherness", "title": "Bring them together, beautifully.", "points": [{"strong": "Brunches, galas, tastings, regattas", "text": "— ticketed events with capacity, seatings, and deposits."}, {"strong": "One-tap RSVP,", "text": "per-guest QR passes, and door check-in from an iPad."}, {"strong": "Resident-only guest lists", "text": "when the evening calls for it."}], "kicker": "The difference between an address and a community is a calendar."}$j$::jsonb),
  ('whitelabel', 13, 'wl-compare', $j${"eyebrow": "The Alternatives", "title": "Build it, patch it — or brand it.", "options": [{"heading": "Build your own", "items": ["Six to twelve months", "Six-figure budget", "Then you maintain it, forever"], "best": false}, {"heading": "Generic tools", "items": ["A different app per tenant", "Someone else's brand", "No concierge, no community"], "best": false}, {"heading": "Balkina, white-label", "items": ["Live in weeks", "Your name, your world only", "Concierge, residents & events included"], "best": true}]}$j$::jsonb),
  ('whitelabel', 14, 'wl-plans', $j${"eyebrow": "The Engagement", "title": "A boutique platform, at a subscription.", "plans": [{"name": "Petite", "price": "€899", "per": "/ month", "text": "For boutique properties. The full concierge, resident membership, events, and your management panel.", "hi": false}, {"name": "Grande", "price": "€2,500", "per": "/ month", "text": "For established destinations with a broad collection of businesses and an active events calendar.", "hi": false}, {"name": "Estate", "price": "€5,600", "per": "/ month", "text": "Up to fifty businesses. Full destination scale — concierge, residents, and events across the property.", "hi": true}, {"name": "Bespoke", "price": "Custom", "per": "", "text": "Beyond fifty businesses, multi-property portfolios, and bespoke integrations — composed to measure.", "hi": false}]}$j$::jsonb),
  ('whitelabel', 15, 'wl-proof', $j${"eyebrow": "In the World", "title_pre": "See it live at", "title_em": "Portonovi", "lede": "A branded concierge app for a luxury marina resort on the Adriatic — on-property booking, verified residents, private events. Your property could be next, in three weeks.", "buttons": [{"label": "Book a private walkthrough", "url": "https://calendly.com/balkina", "style": "gold"}, {"label": "Experience Portonovi live", "url": "https://balkina.ai", "style": "line"}]}$j$::jsonb)
) AS v(deck, position, template, content)
WHERE NOT EXISTS (SELECT 1 FROM deck_slides);
